### ISSUE TITLE
Android folder is empty on Android 11

### ISSUE THREAD

**Issue by LSDsl** [XayahSuSuSu/libpickyou#3]
Not show data, media and obb subfolders in Android folder

**Comment by XayahSuSuSu** [comment]
> Not show data, media and obb subfolders in Android folder

It's accessible with root.
And the classic ways to get permission of Android/data don't work on Android 12+, I'm still looking for ways to solve that.

**Comment by LSDsl** [comment]
Could you add support for Android 11 for now (without root)? Many file explorers can do this.

**Comment by XayahSuSuSu** [comment]
> Could you add support for Android 11 for now (without root)? Many file explorers can do this.

Ofc, will do that if available

**Comment by XayahSuSuSu** [comment]
New implementation: [fsaf](https://github.com/K1rakishou/Fuck-Storage-Access-Framework), [example](https://github.com/folderv/androidDataWithoutRootAPI33)

**Comment by XayahSuSuSu** [comment]
Implemented in [2.1.6](https://github.com/XayahSuSuSu/libpickyou/releases/tag/2.1.6)
