### ISSUE TITLE
[Bug] Files/Dirs not fully displayed at /

### ISSUE THREAD

**Issue by XayahSuSuSu** [XayahSuSuSu/libpickyou#4]

**Comment by XayahSuSuSu** [comment]
@mymine
Can you have a test for it?
[app-debug.zip](https://github.com/XayahSuSuSu/AndroidModule-PickYou/files/12826154/app-debug.zip)

**Comment by mymine** [comment]
> @mymine Can you have a test for it? [app-debug.zip](https://github.com/XayahSuSuSu/AndroidModule-PickYou/files/12826154/app-debug.zip)

![Uploading Screenshot_2023-10-06-10-07-37-921_com.xayah.pickyou.jpg…]()
可以了
