### ISSUE TITLE
FR: Predictive back support

### ISSUE THREAD

**Issue by asuka-mio** [XayahSuSuSu/libpickyou#6]
https://github.com/XayahSuSuSu/AndroidModule-PickYou/blob/12ec2287d6021be548b770c05fbb16bb09609751/libpickyou/src/main/java/com/xayah/libpickyou/ui/activity/LibPickYouActivity.kt#L69
This may break activity preview of Predictive Back

**Comment by XayahSuSuSu** [comment]
Any solutions?
Switch to `BackHandler { }`?

**Comment by asuka-mio** [comment]
> Any solutions? Switch to `BackHandler { }`?

Hold a reference to callback, and disable that callback if necessary
